name: "Build and Tests"
on:
  pull_request:
  push:
    paths-ignore:
    - 'README.md'
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.13.x
          - 4.14.x

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@master
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: "Install dependencies"
        run: opam install . --deps-only --with-test

      - name: Check autoformatting
        run: eval $(opam env) && dune build @fmt

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
